// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rehwdwcolzgpfgnpeqgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlaHdkd2NvbHpncGZnbnBlcWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjE5NzQsImV4cCI6MjA1OTEzNzk3NH0.GmCTw0iIkN5d_SfBeshdwZq2oVWJC1ELn6PH5HSqcCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);